Thisis for refresshing my memory as i have not done any programming in a while
# Python code to demonstrate the use pandas

In [1]:
import pandas as pd
import numpy as np

In [3]:
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 2.2.3
NumPy version: 2.2.4

In [7]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['A', 'B', 'C'])

In [13]:
df.head()

   X  Y  Z
0  1  2  3
1  4  5  6
2  7  8  9

In [17]:
df.columns = ['X', 'Y', 'Z']
df.head()

   X  Y  Z
0  1  2  3
1  4  5  6
2  7  8  9

In [18]:
df.describe()

         X    Y    Z
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [24]:
df.nunique()

X    3
Y    3
Z    3
dtype: int64

working with olympic data

In [ ]:
coffee = pd.read_csv(r'C:\Users\OGTL_ADMIN\Desktop\somto\pandas\data\warmup-data\coffee.csv')

To be continued by students <br/>
https://youtu.be/2uvysYbKdjM?si=6COk5rXgqJQiOm7Y